### ISSUE TITLE
pip

### ISSUE THREAD

**Issue by chaddotson** [python-semver/python-semver#105]
Is this library fully compatible with the semantic versioning recognized by pip?

**Comment by tomschr** [comment]
@chaddotson 
I'm not the maintainer of this project so take this information with some caution.

As far as I can see, this library is NOT "fully compatible" with pip. If you search the pip directories for "version" you get some matches in the module `pip._vendor.packaging.version` with the classes 
`_BaseVersion`,  `LegacyVersion`, and `Version`.

The seem to contain a completely different API than semver.

**Comment by tomschr** [comment]
@chaddotson Thank you for your contribution! :+1: 

I think, I've answered this question and close this bug for the time being. If you think, there is something else you need to know, just let us know.
