### ISSUE TITLE
Library is partially non-compliant with semver spec

### ISSUE THREAD

**Issue by dbarella** [python-semver/python-semver#114]
Breaking input: `0.0.0-0foo.1`

Expected result:

```
>>> import semver
>>> semver.parse('0.0.0-0foo.1')
{'build': None, 'major': 0, 'patch': 0, 'minor': 0, 'prerelease': '0foo.1'}
```

Actual result:

```
>>> import semver
>>> semver.parse('0.0.0-0foo.1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/semver.py", line 65, in parse
    raise ValueError('%s is not valid SemVer string' % version)
ValueError: 0.0.0-0foo.1 is not valid SemVer string
```

Per [item 9](https://semver.org/#spec-item-9), only numeric IDs cannot contain leading zeros -- since `0foo` is not entirely numeric, it may contain a leading zero.

**Comment by scls19fr** [comment]
I also understand it this way:

    Numeric identifiers MUST NOT include leading zeroes.

so

    Non numeric identifiers MAY include leading zeroes.


What is your opinion @k-bx ?

PR (with fix and test) are welcome @dbarella !

**Comment by sirzooro** [comment]
Any update on this? We use git commit hash as a prerelease part, so sometimes we trigger this error too.

**Comment by tomschr** [comment]
If I'm not mistaken, it is related (or a duplicate?) of #194.

**Comment by sirzooro** [comment]
Yes, it is a duplicate. You can close this issue.

**Comment by tomschr** [comment]
Duplicate of #194 so closing.
