### ISSUE TITLE
Optionally be able to work with leading 'v'

### ISSUE THREAD

**Issue by ialidzhikov** [python-semver/python-semver#137]
Currently

```
semver.parse_version_info("v0.1.0")
```

fails with 

```
ValueError: v0.1.0 is not valid SemVer string
```

However the leading `v` is not included in the semver spec (https://semver.org), but the master branch of semver/semver has the following faq section - https://github.com/semver/semver/blob/master/semver.md#is-v123-a-semantic-version :
> Is "v1.2.3" a semantic version?
No, "v1.2.3" is not a semantic version. However, prefixing a semantic version with a "v" is a common way (in English) to indicate it is a version number. Abbreviating "version" as "v" is often seen with version control. Example: git tag v1.2.3 -m "Release version 1.2.3", in which case "v1.2.3" is a tag name and the semantic version is "1.2.3".

The golang and go modules requires the leading `v` and almost every project relies with the convention (for example kubernetes/kubernetes, docker/docker and etc.).

[Masterminds/semver](https://github.com/Masterminds/semver) (the golang equivalent of this project) can optionally work with a `v` prefix.

**Comment by ialidzhikov** [comment]
@scls19fr , @Flamefire any feedback?

**Comment by Flamefire** [comment]
For easy use I'd allow a leading v and have a param "strict" check to disallow it with a default (I'd choose false to match others) 

But I'm not the author so can't decide this

**Comment by kxepal** [comment]
Why not just normalize version string (strip any `v`-like prefixes) before pass it to semver? This is quite simple operation and requires no changes for this project.

**Comment by ialidzhikov** [comment]
> Why not just normalize version string (strip any `v`-like prefixes) before pass it to semver? This is quite simple operation and requires no changes for this project.

Yep. But this will force the client to know whether he/she truncated leading 'v' and after the interaction with semver to append again the leading 'v' to the output.

**Comment by kxepal** [comment]
And only the client knowns about what prefix was used and how to deal with it. It could be `v` or project name like `semver-1.2.3`.

**Comment by tomschr** [comment]
That issue looks very similar to #210 which I've done lately. We've come to the conclusion that we do not want to support a function which doesn't adhere to the semver specification. That means, we avoid partial parsing of a version string.

However, to support our developers, we think to add some recommendations to our documentation is a good idea. As such, I've written a short section into our documentation (see PR #215: "Dealing with Invalid Versions").

@scls19fr With that background, I think, we can close this issue, right?

**Comment by xor-gate** [comment]
The semver spec says indeed it is not a valid version string when prefixing with "v" but it is a very common practice. Because it is not supported in the parse by just checking if the prefix character 'v' exists and stripping it everybody which uses the v prefix need to strip it. It would be more nice to put it inside the parser.
