### ISSUE TITLE
Python Support for Batch File is Wrong

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#153]
## Situation

the SVG image file in the `README.rst` contains the following string:

```
2.7 | 3.2 | 3.3 | 3.4 | 3.5 | 3.6
```

However, that contradicts the `setup.py` metadata, which contains support for 2.7 and >=3.4.

Additionally, it seems, PyPI has some old data. When you open https://pypi.org/project/semver/ and scroll down a bit, you see:

```
 Programming Language
    Python
    Python :: 2
    Python :: 2.7
    Python :: 3
    Python :: 3.2
    Python :: 3.3
    Python :: 3.4
    Python :: 3.5
    Python :: 3.6
```

## Proposed Solution

Some of these should help: :wink:  

* Adjust the batch
* Adjust the `setup.py` file.
* Create a new release with the correct data

**Comment by ppkt** [comment]
It's correct, data is taken from latest *published* version on PyPI: https://github.com/k-bx/python-semver/blob/2.8.1/setup.py
There is a ticket for 2.9.0 release (#134) but it was blocked by few PRs @scls19fr would like to include.

**Comment by tomschr** [comment]
Yes, probably it's covered when a new release is done. If you like, you can close this issue.
Just wanted to help. :-)

**Comment by ppkt** [comment]
Oh no, I just wanted to say that no action is necessary to fix this issue. Some time ago I also checked why Python 3.7 isn't listed in PyPI and I found SO post explaining this :)

**Comment by tomschr** [comment]
Ok, so I'll close this issue for the time being. :wink:  Thanks for your patience. :-)
