### ISSUE TITLE
Document state of Python 2.7 support

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#161]
## Situation

At the moment, this project uses and supports Python 2.7. As we all know, Python 2.7 is going out of maintenance soon ("retire") and it's not clear what the project is going to do.

After disussing #160, we found out that the project doesn't have a clear statement or information regarding the retirement of Python 2.7 (neither in issues, README, nor documentation). Maybe I have missed something; in that case we can close this issue. :wink: 

We are currently lacking answers of the following questions:

* For how long do we want to support Python 2.7?
* Which semver version(s) still support Python 2.7?
* Do we want to have semver 3.x.y which supports only Python 3.x?

## Suggested Solution

Whatever the project decides, we need to document it. :wink: What about the following approach?

* Add a short note, paragraph, section etc. about the retirement of Python 2.7 inside our README. Maybe even link to this issue.
* Focus in our documentation on Python3 only.

Apart from the documentation issues, I would also propose to indicate such a change with raising the major version of semver. For example:

* 2.x: would still contain the support for Python 2.7
* 3.x: would be the main line without support for Python 2.7 (in other words, >= Python 3.5 only)

Luckily, such major versions match with the Python version. :wink: 

Would that help?

## See also

* https://pythonclock.org/
* https://www.python.org/dev/peps/pep-0373/

**Comment by scls19fr** [comment]
My opinion (my 2cts)

We will release in the next coming days / weeks a 2.9.x version of python-semver which will support Python 2.7 and 3.x

After this, we will be working on a 3.x version of python-semver which will only support Python 3.x

I won't personally backport python-semver 3.x features to 2.x branch to urge people to leave this venerable Python 2.7 version (in life everything stops one day :wink: ) 

Releasing is time consuming... releasing 2 versions can be more than 2 times consuming.

**Comment by ppkt** [comment]
I fully agree - I think we should only fix bugs in 2.x branch.

Another question - what about Python 3.4? It's marked as EOL and maybe we should remove support for that version as well in 3.x?

**Comment by tomschr** [comment]
> Another question - what about Python 3.4?

I was thinking the same. Maybe we can mark this version also as unsupported in our upcoming 3.x branch?

**Comment by scls19fr** [comment]
Agree no Python 3.4 in python-semver 3.x but Python 2.7, 3.4 in python-semver 2.9.x

**Comment by tomschr** [comment]
Ok, great! So to summarize the needed actions:

* [ ] Add the current document state/idea into the README
* [ ] Create a 2.9.x release
* [ ] Open a `maint/2.9.x`(?) maintenance release branch. 
  This would be only for interested people, no backporting will happen
* [ ] Create a 3.x release with the subtasks:
  * [ ] Remove test target  `py27`
  * [ ] If needed, remove/refactor code that was introduced only for Python 2.7
  * [ ] If needed, "optimize" code for Python3
  * [ ] Focus on Python3 in the documentation

Anything else?

**Comment by tomschr** [comment]
I'd suggest to make our user base aware of such an incompatible change and add a warning notice in our README file:

```rst
.. warning::

   Major version 3.0.0 of semver will remove support for Python 2.7 and 3.4.

   As anything comes to an end, this project will focus on Python 3.x. New
   features and bugfixes will be integrated only into the 3.x.y line of semver.

   The last version of semver which supports Python 2.7 and 3.4 will be
   2.9.x. However, keep in mind, version 2.9.x is frozen: no new
   features nor backports will be integrated.

   We recommend to upgrade your workflow to Python 3.x to gain support,
   bugfixes, and new features.
```

**Comment by scls19fr** [comment]
LGTM

**Comment by tomschr** [comment]
@scls19fr 
Thanks for merging it, :+1:  but it's only one part of it. I've mentioned other items in my https://github.com/k-bx/python-semver/issues/161#issuecomment-539045512.

Should we transfer the other, unresolved items into a new issue or is it better to reopen this issue?

**Comment by scls19fr** [comment]
Ok so let's reopen and adress remaining items.

**Comment by tomschr** [comment]
The comment https://github.com/k-bx/python-semver/issues/161#issuecomment-539045512
that mentions Python 3/semver 3.0.0 is covered in a separate issue #176 now.

**Comment by tomschr** [comment]
@python-semver/reviewers 
As far as I can see, from https://github.com/python-semver/python-semver/issues/161#issuecomment-539045512, only the maintenance branch is open:

> Open a `maint/2.9.x(?)` maintenance release branch (choose a name you like).
This would be only for interested people, no backporting will happen

When should we create such a branch? (As Python 2 is now EOL). 

Probably we want to create another release before, right?

**Comment by eli-darkly** [comment]
I'm confused by the statement in the Readme that seems to say 2.10.0 _does_ still support Python 2.7. That's not what I'm seeing. I have a project that uses this package and runs in Py2, and as soon as it started using the 2.10 release, I started getting errors like this which look to me like what you'd get from a Py2 vs. Py3 incompatibility:

`TypeError("Expected str or VersionInfo instance, but got <type 'unicode'>"`

When I pin the dependency to `<2.10`, the error goes away.

**Comment by tomschr** [comment]
@eli-darkly Thanks Eli! :+1: Much appreciate your bug report. I've opened #274.

If I'm not mistaken, I assume this is of some `if isinstance(other, str)` lines which didn't recognize the `unicode` datatype in Python2.

**Comment by tomschr** [comment]
I've opened a maintenance branch `maint/v2` if we need that for the semver v2 line.
I think, all tasks are done so I'm closing this issue for the time being.
