### ISSUE TITLE
Consider creating a semver package

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#169]
## Definitions

* **Module**
  A module is a file containing Python definitions and statements.
* **Package**
  A package is a collection of modules in directories that give a package hierarchy.

## Situation

The current `semver.py` module contains almost 800 lines of code. As new functionality is added, the files grows bigger and bigger. 

## Suggested Solution

Should we consider to refactor the semver module into a package?

If yes, this is a feature which we should introduce for the upcoming 3.0.0 release. Could we label that in GitHub as such (or create a milestone)? :wink: 

Maybe we should also consider to refactor our test cases too and move them to a `tests/` directory and create different files? They are currently almost 700 lines of code.

That issue involves the following actions:

* [ ] refactor semver module into package
* [ ] Probably introduce a `tests/` directory?

```
semver/
├── __main__.py  # basically imports semver.cli.main and runs main()
├── __init__.py  # should contain only the usual constants like __version__, __author__ etc.
├── cli.py       # implements the command line interface
└── [... probably more files ...]
```

An example (although a bit outdated now as new commits arrived in master) can be viewed in 
[my fork)](https://github.com/tomschr/python-semver/tree/bugfix/59-cli-module/src/semver). It's not perfect, but a start.

### Pros

* Make files smaller and more readable
* No API change to the user
* Easier to add more functionality
* With `__main__.py`, it is possible to use `python -m semver -h`

### Cons
* More files means also, to search where a function is defined
* Slightly more difficult to test as it may be needed to run `tox` first or create a virtual environment.

What do you think? :wink:

**Comment by scls19fr** [comment]
+1 as it will also reduce the possibility of having conflicts.

But maybe we should consider this for a 3.0.0 release

**Comment by tlaferriere** [comment]
I believe that the pros here really outweigh the cons:

> * More files means also, to search where a function is defined

A well named file will contain relevant functions, therefore narrows down where you could possibly find a function related to a specific feature.
As for the edge cases, that's what IDEs are for, right? 😜 

> * Slightly more difficult to test as it may be needed to run tox first or create a virtual environment.

Relative imports still work when breaking up a module into a package.
Also, once the config is written and just works, you probably will never touch it again.

I would give this a +2 if I could since the `semver.py` file is starting to bloat with some mutually irrelevant functionalities (not irrelevant to the package, mind you, to each other only).

**Comment by tlaferriere** [comment]
> Probably introduce a tests/ directory?

That is an interesting question 🤔 ...

From my personal experience, most python packages I've worked with tend to have a `tests` directory that mirrors the package they are testing.  
OTOH, I've enjoyed working with frameworks (like Angular, to name one) that have the test module in the same directory as the module they are testing, as it brings the tests closer to the code, and I've read in many python testing frameworks that they support discovering tests pretty much anywhere, referring to this kind of organisation.

Out of familiarity, I would be tempted to go with the former for the usual pro: it is easier to exclude test code collecting files for packaging.

**Comment by tomschr** [comment]
> I believe that the pros here really outweigh the cons:
>
> > * More files means also, to search where a function is defined
> 
> A well named file will contain relevant functions, therefore narrows down where you could possibly find a function related to a specific feature.
> As for the edge cases, that's what IDEs are for, right? 

In theory yes. But not everybody uses IDEs.

 
> > * Slightly more difficult to test as it may be needed to run tox first or create a virtual environment.
> 
> Relative imports still work when breaking up a module into a package.
> Also, once the config is written and just works, you probably will never touch it again.

Right.

> I would give this a +2 if I could since the `semver.py` file is starting to bloat with some mutually irrelevant functionalities (not irrelevant to the package, mind you, to each other only).

Yes, that would probably help to focus and consolidate.

**Comment by tomschr** [comment]
> > Probably introduce a tests/ directory?
> 
> That is an interesting question  ...
> 
> From my personal experience, most python packages I've worked with tend to have a `tests` directory that mirrors the package they are testing.
> OTOH, I've enjoyed working with frameworks (like Angular, to name one) that have the test module in the same directory as the module they are testing, as it brings the tests closer to the code, and I've read in many python testing frameworks that they support discovering tests pretty much anywhere, referring to this kind of organisation.

You are right, test frameworks can discover tests almost anywhere. From a technical side, it doesn't matter where they are. It's probably a matter of taste.

> Out of familiarity, I would be tempted to go with the former for the usual pro: it is easier to exclude test code collecting files for packaging.

Exactly. I prefer a separate `tests/` directory as I believe, it shouldn't be installed with the code. It's a method to help developers, but for users it's pretty useless.

**Comment by tlaferriere** [comment]
Looking at the current direction the project is taking, I think we will have 2 files:
* `version_info.py`: contains the `VersionInfo` class
* `cli.py`: contains all the functions used for the cli.

Seeing that most module level functions are now being deprecated, I think this layout will be clear and it shouldn't be too hard to search for a functionality.

**Comment by tomschr** [comment]
> Seeing that most module level functions are now being deprecated, I think this layout will be clear and it shouldn't be too hard to search for a functionality.

Yes, I think so too. If it turns out we should keep one or two module level functions, we could create a third file.

**Comment by tomschr** [comment]
This is now integrated in #306
