### ISSUE TITLE
Prepare semver 3.0.0

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#176]
## Situation

As we have released 2.9.0 of semver, we should consider of moving to 3.0.0 soon. This is needed to start working on adding new features and optimizing source code for Python 3.

(I've created this issue to make the upcoming 3.0.0 more visible and to have a record when we need to search the history.)

## Suggested Solution

In order to create semver 3.0.0, we need to think about the following tasks:

* [x] Create a maintenance branch for 2.x.y line: `maint/v2`
* [x] Remove test target `py27` and `py34` from `tox.ini`
* [x] Tag the 2.9.0 release.
* [x] Update the Trove classifiers in `setup.py` and remove support for Python 2.7 and 3.4.
* [x] Optimize source code for Python 3 only and remove any code that was introduced due to 2.7.
* [x] Provide (and label it correctly) the 2.9.0 documentation for ReadTheDocs.
   We need a configuration that should be possible that old (2.9.x) and new versions (3.*) are still available and can coexit together peacefully. :wink: 
* [ ] Change version number in master to 3.0.0.

Anything else? :wink: 

I've updated the description in https://github.com/k-bx/python-semver/issues/161#issuecomment-539045512 of issue #161

**Comment by scls19fr** [comment]
> Tag the 2.9.0 release

I think it's ever the case... a 2.9.0 release [have ever been tagged](https://github.com/k-bx/python-semver/releases/tag/2.9.0)

**Comment by tomschr** [comment]
> > Tag the 2.9.0 release
> 
> I think it's ever the case... a 2.9.0 release [have ever been tagged](https://github.com/k-bx/python-semver/releases/tag/2.9.0)


Yes, I just mention it to not forget about it. :wink: I've checked it now.

**Comment by ppkt** [comment]
a quick question - do we have any branch for 3.0.0 release?

**Comment by tomschr** [comment]
@ppkt as far as I know, not now. I have some ideas in my mind which I would like to apply to a 3.0.0 only release. :wink: 

My impression was to wait(?) until Python 2.7 is EOL in January 2020. Maybe I got it wrong.

Well, anyway, it should be fairly easy to create a new branch. :wink:

**Comment by tomschr** [comment]
Checked "Provide (and label it correctly) the 2.9.0 documentation for ReadTheDocs."

**Comment by tlaferriere** [comment]
I have just read that python 3.5 has reached end of life. I think we should go ahead and focus on supporting python >= 3.6 since there are quite a few features relating to type hints that could be useful to us that were only added in 3.6.

**Comment by tomschr** [comment]
Good catch! Thanks for the hint! I've updated `setup.py` and `tox.ini`.
