### ISSUE TITLE
Move k-bx/python-semver to python-semver/python-semver / transfer ownership of k-bx/python-semver to python-semver Github organization

### ISSUE THREAD

**Issue by scls19fr** [python-semver/python-semver#177]
Hi all,

as discussed in https://github.com/k-bx/python-semver/issues/134#issuecomment-548312845
a Github organization https://github.com/python-semver/ have been created (@k-bx and I are currently owner).

We need https://github.com/k-bx/python-semver/ to be moved to this organisation (ie k-bx/python-semver ownership should be transferred to https://github.com/python-semver/ ).

In order to keep issues history, I think you will need to transfer ownership of https://github.com/k-bx/python-semver to https://github.com/python-semver/ Github org.

https://help.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

After this, some setup will probably be required (Continuous Integration, maybe some links in project files...)

Maybe we should probably use this occasion to setup https://travis-ci.com/ instead of https://travis-ci.org/
https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/

https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com/4305

> New users and projects (both private and public) should only use travis-ci.com

Your opinion?

Kind regards

**Comment by tomschr** [comment]
> Maybe we should probably use this occasion to setup Travis [...]

Just to let you all know: GitHub has released [GitHub Actions](https://help.github.com/en/github/automating-your-workflow-with-github-actions/about-actions) now. To see it how we can use it, in my fork I've added an action to release semver to test.pypi.org, see here: https://github.com/tomschr/python-semver/actions

I don't have anything against Travis, it's just another CI we could consider (as we rebuild our repo anyway). 

* GH Actions are done completely "inside" GH. If this is a bad thing or a good thing is up to you.
* We can have specific GH Actions in our GH org which is created for *our* workflow. These Actions just reside in another repo of our org.

Any preferences for Travis or GH Actions? :wink: 

-----

Another point is do we need teams? Teams can be created with specific permissions. For example, we could create a release team or some admins etc. That makes it a bit easier to distribute the work (of course, communication is still essential).

Maybe we don't need to decide it now, it can be added in the future. With a GH org it's kind of very easy to do that.

**Comment by tomschr** [comment]
Ok, here is a short checklist that may be helpful:

* [ ] Move `k-bx/python-semver`  repo to `python-semver/semver` (?)
* [ ] Adapt link to new org/repo in `setup.py`, documentation, READMEs etc.
* [ ] Adapt config for PyPI?
* [ ] Adapt config for ReadTheDocs?
* [ ] "Announce" it somewhere? Social channels? Maybe add a short notice in our README?

If you have further ideas, please amend it! :+1:

**Comment by scls19fr** [comment]
logo should be our top priority 😉😉😉

about doc... github page can also be considered

**Comment by tomschr** [comment]
> about doc... github page can also be considered

True, I thought of that as well. But I'm not sure how easy is setting it up to store different versions. I haven't looked at ReadTheDocs, but I *assume*, it can be a little bit easier.

**Comment by scls19fr** [comment]
Thanks @k-bx for having transfered python-semver.

I personally don't see any problem about having project available at

https://github.com/python-semver/python-semver/

I will now see about CI transfer (still using Travis), url fix...

After this, I will grant @tomschr some rights to test CI using Github actions.

**Comment by scls19fr** [comment]
https://github.com/python-semver/python-semver/pull/178 should fix all (most?) links to GH org now.

I have also changed in https://readthedocs.org/dashboard/python-semver/edit/ repository URL
and added @tomschr as maintainer of doc on RTD where he should be able to do some light "experiments" (especially about historization of documentation versions).

**Comment by tomschr** [comment]
@scls19fr Thank you very much! :heart: :+1: I will read the docs how to host different versions. Will let you know once i'm done. :wink:

**Comment by tomschr** [comment]
@scls19fr 
> maintainer of doc on RTD where he should be able to do some light "experiments" (especially about historization of documentation versions).

I did some light experiments and activated two previous version (2.9.0 and 2.8.1). Just for testing. I think, we should keep 2.9.0 but can delete 2.8.1.

That was easy! Any other wishes? :wink:

**Comment by ppkt** [comment]
@tomschr I would keep previous versions - not everyone will have ability to use latest version of package (for instance in case of using package from their distro)

**Comment by tomschr** [comment]
@ppkt  Right Karol. Which versions would you keep?

**Comment by ppkt** [comment]
@tomschr let's start from 2.8.1 (however in Debian there is still 2.0.1)

**Comment by tomschr** [comment]
@ppkt That is already the case. :wink:  I've enabled 2.8.1 and 2.9.0. Additionally,  we have "latest" and "stable", but these are just links to the current 2.9.0 version.

However, that will change of course when we release 3.0.0 (or 2.9.1, whatever).

**Comment by scls19fr** [comment]
We had this quite old issue https://github.com/python-semver/python-semver/issues/95 about triggering doc build (at least "latest") at each commit.
Maybe @tomschr you can have a look at this to avoid the need of manually triggering doc compilation.

**Comment by tomschr** [comment]
@scls19fr Ahh, right, I remember. :)
I looked at it and it seems there is a problem with the GitHub webhook. I've tried to "resync" it, but it seems, RTD needs additional admin permissions which I don't have. 

From what I saw, it looks normal in the RTD. Maybe you could try to remove the Webhook and readd it? Maybe that solves the problem.

**Comment by scls19fr** [comment]
@tomschr you should now be allowed to remove/add webhook in this repository.

**Comment by tomschr** [comment]
@scls19fr Thanks, I've recreated it, but I couldn't test it. Maybe we should create a 2.9.1 anyway, because the Changelog has a (WIP) label.

**Comment by scls19fr** [comment]
high permission high responsibility.
I noticed you @tomschr have 2FA enabled in your Github account which is a very good idea!
Being hacked some times (especially on social networks) I can recommand to @k-bx to do it also.

**Comment by scls19fr** [comment]
Not sure publishing a new release just for changing CHANGELOG is worth it.
(I don't have currently access to CLI to publish to Pypi... just to GH through website)

Maybe we should tackle "real" issues

**Comment by scls19fr** [comment]
Not sure the doc build is automatically triggered
because I merged https://github.com/python-semver/python-semver/pull/178 5 minutes ago but latest doc compilation is still 1 hour, 20 minutes ago according https://readthedocs.org/projects/python-semver/

**Comment by tomschr** [comment]
> Not sure the doc build is automatically triggered

I think it did. The last build is 49min back (https://readthedocs.org/projects/python-semver/builds/9913706/) which built commit  e2b07af2e

> Not sure publishing a new release just for changing CHANGELOG is worth it.

Right, I think my idea is obsolete as the Webhook seems to work (as trying to show it in the previous paragraph).

Thanks for your changes and the trust you put in me. :-)

**Comment by tomschr** [comment]
@scls19fr Could we close this issue? :wink: 
According to https://github.com/python-semver/python-semver/issues/177#issuecomment-549272560 we have these two open items:

* Maybe create dedicated teams?
* Adapt config for PyPI?

I guess, we don't need teams at the moment. Do we need a special config for PyPI? Or do you see other things that needs to be fixed for this issue? Thanks!
