### ISSUE TITLE
Infra: Protect master?

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#180]
## Situation

Currently, our master branch is "unprotected". That means, you could force-push commits or delete the branch accidentally (would be a bad idea anyway).

(I've labled it with "infra" to make it clear that this issue has anything to do with source code, but with the infrastructure of this project.)

## Proposed Solution

Before I change something, it's better to discuss it. I'm talking about the [branch protection rule](https://github.com/python-semver/python-semver/settings/branch_protection_rules/new) settings.

If we enable it for master, we get:

* Disables force-pushes to all matching branches and prevents them from being deleted.

Apart from the force-push protection, we *could* enable additional rules:

* Require pull request reviews before merging
* Require status checks to pass before merging
* Require signed commits
* Include administrators
* Restrict who can push to matching branches

I'm unsure if such rules are really necessary or are useful for this project. At the moment, I think, it's enough to protect master from being force-pushed or deleted.

Your opinions? :wink:

**Comment by scls19fr** [comment]
+1 about protecting master branch.
I'm also doing this for some repositories to protect some of my projects against myself 

other protection rules may be a bit overkilled

**Comment by scls19fr** [comment]
Here's branch protection rule setup I've done.

![Capture d’écran 2019-11-05 à 19 33 08](https://user-images.githubusercontent.com/109167/68235229-2a221500-0003-11ea-9203-25815b9965f5.png)

If you are ok with that you can close issue

**Comment by scls19fr** [comment]
Oh... sorry I forget to also tick "Include administrators".
That's done now.

I'm unsure if "Require branches to be up to date before merging" should be ticked or not.

Opinion?

**Comment by tomschr** [comment]
Thanks for the feedback! Much appreciated! :+1: 

Good points! I've checked what you've recommended.

The other option is described as:

* Require branches to be up to date before merging

  This ensures pull requests targeting a matching branch have been tested with the latest code. This setting will not take effect unless at least one status check is enabled (see below). 

Not sure about that... :thinking:

**Comment by tomschr** [comment]
Nevertheless, I think we can close it. :+1: :smile_cat:
