### ISSUE TITLE
Infra: When and how to prepare the 2.10.x line?

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#183]
## Situation

We've decided to freeze 2.10.x and no new features will be added to this version (except security and severe bugfixes). As we are going towards 3.0.0, master will contain the new version soon.

However, we still haven't thought about how to deal/manage both versions, old and new, so they can live peacefully together.

## Proposed Solution

Probably we should open a maintenance branch for the 2.10.x line. The open questions are:

* When should we open the maintenance branch? Now or in the not so far future?
* How should we deal with upcoming 2.10.x versions? 

Here is my idea that I would like to discuss with you:

1. Make sure we have a clean, good state (should be already the case; but it doesn't hurt to look a bit deeper).
1. Branch off from current master and create a `maint/2.10.0` branch. We could also use `stable/2.10.0`. Any better name? :wink: 
1. Change version in master to 3.0.0+alpha1 (just an example). 
1. Optionally indicate it in the README as "work in progress".
1. Now we can start implementing code for 3.0.0 only.

After these steps, we have the new version in master and the old version in a maintenance branch. If and how we want to create a new release for the 2.10.x line, it's a matter of taste. One way to do it could be like this:

1. Add the changes to the 2.10.0 maintenance branch.
1. Raise version to 2.10.x.
1. Tag the release.
1. Publish the 2.10.x release.

It could be helpful to protect the maintenance branch like we did with master.

Anything else we need to cover? Comments? :wink: 

----

Update: Changed 2.9.x -> 2.10.0

**Comment by scls19fr** [comment]
I would let Python 2.7 die before
https://pythonclock.org/
2 months is not so long...

**Comment by ppkt** [comment]
I think we could create this branch right now and start adding things for Py3.5+ only but it's only my opinion :)

**Comment by tomschr** [comment]
@ppkt 
Yes, I would have no problem to create a maintenance branch release for the 2.9.x series and adding new feature in the master branch (which would be the upcoming 3.0.0 release). I would love to start for the next major release. :wink: 

Of course, there are other ways to do it, like creating a dedicated 3.0.0-pre release branch, adding stuff there and then merge it to master when it's "ready".

Personally, I would prefer the first method (create a 2.9.x maintenance branch, master will be the upcoming 3.0.0 release). I think, it makes it a little bit easier.

**Comment by tomschr** [comment]
Currently, we have one problem and that is Travis. For some reason, it doesn't seem to finish it's task and blocks our pull requests. :disappointed: I'm not sure how to fix it...

**Comment by ppkt** [comment]
@tomschr agree, I think separate branches for 2.9.x and 3.0.x would be great (so we could consider master as "stable" branch).

**Comment by tomschr** [comment]
@ppkt Whatever works is fine for me. :wink: Let's see what @scls19fr has to say about that.

What would you prefer? Would you wait til January (as indicated in some other comment)? Or can we start right away? :wink:

**Comment by scls19fr** [comment]
Submitting PR is always opened and discussion can occur on these PR.
We will see in January for merging them to master.
Maybe we should have a tag WIP (and/or Release 3.x.y) to just remember not to merge them.
I don't think we have enough human ressources for managing several branches (even if here *several* means 2 :smile: )
In January we will create a 2.9.x branch before merging 3.x features to master.
So our 3.x.y development will be in master and we will have a 2.9.x branch if we need to go back (hoping that we won't need to do it)

**Comment by tomschr** [comment]
> Maybe we should have a tag WIP (and/or Release 3.x.y) to just remember not to merge them.

That would be one way. Another way would be to open PRs as "Draft". If you do that, merging is disabled unless you change "Draft" to "Ready for review".

**Comment by scls19fr** [comment]
I never used previously PR as Draft but it seems to be a good idea as it will be a place to have discussion about changes we expect to be merged for 3.x.y.

**Comment by tomschr** [comment]
@scls19fr, @ppkt any new ideas how to proceed? Should we create a 2.9.1 release before we switch to 3.0.0?

For the major 3 release, I've created the [release 3 project](https://github.com/python-semver/python-semver/projects/1). Would it make sense to create something similar for the 2.9.1 release?

**Comment by tomschr** [comment]
As we are preparing a 2.10.0 in #237 soon, this issue is related to it.

@python-semver/reviewers
Once 2.10.0 is released, I would suggest to work on the semver3 after. IMHO, that gives us the chance to remove all the old stuff of Python2 and focus on one code base.

Any concerns or objections about this idea? :wink:

**Comment by tomschr** [comment]
I guess, this is solved by #246
