### ISSUE TITLE
Infra: PyPi page contains wrong links

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#184]
## Situation

Our project page on https://pypi.org/project/semver/ contains two wrong links on the left sidebar, see the "Project links" category and the links "Homepage" and "Download" . They still point to k-bx. :wink: 

Although it still works, we shouldn't propagate the old links anymore.

## Proposed Solution

It should be fairly easy to fix it (however, I don't have write permission on PyPI): replace `k-bx` with `python-semver`.

**Comment by scls19fr** [comment]
That's odd

![Capture d’écran 2019-11-08 à 17 10 11](https://user-images.githubusercontent.com/109167/68491221-b96d3980-024a-11ea-8e1c-dcb521fd73e3.png)

Despite I'm maintainer of python-semver project "Manage" button is disabled.

So I can't currently change link.

Maybe @k-bx can.

Or that's a problem on Pypi side.

**Comment by scls19fr** [comment]
In fact the problem seems to appears because "Owner" role is required.

See https://github.com/pypa/warehouse/issues/6217

**Comment by tomschr** [comment]
@scls19fr Thanks for investigating this. Much appreciated. :+1: 

Maybe @k-bx should give you owner rights? :wink: Or maybe we should better contact him by mail.

**Comment by k-bx** [comment]
made scks an owner on pypi. cheers!

**Comment by scls19fr** [comment]
Thanks @k-bx 
I will change url as discussed here.

**Comment by scls19fr** [comment]
I've just see in Pypi  Admin page of [python-semver](https://pypi.org/manage/project/semver/settings/)

> Project description and sidebar
> To set the 'semver' description, author, links, classifiers, and other details for your next release, use the setup() arguments in your setup.py file. Updating these fields will not change the metadata for past releases. Additionally, you must use Twine to upload your files in order to get full support for these fields. See the Python Packaging User Guide for more help.

it seems that we can't set url from admin page but only when pushing new release (and only when using twine)

For example, our `setup.py` have new url https://github.com/python-semver/python-semver/ but this field haven't been updated during latest release...

My guess...  we should have a deeper look at #173 because publishing new release should be done only using twine.

**Comment by tomschr** [comment]
@scls19fr Thanks for investigating this! :+1:

One question: would it be possible to delete the latest release on PyPI and rerelease it again (with twine or whatever is needed)?

**Comment by scls19fr** [comment]
I don't think it's a good idea to delete release. I can even say that it's a very bad idea.
We can publish an other one if necessary (bumping patch version).

**Comment by tomschr** [comment]
Ahh, you are right of course. I was stuck in the thought that you tried to fix it for 2.9.0 *only*. :-)

**Comment by tomschr** [comment]
I can't see this problem anymore in PyPI, so I think this is fixed.
