### ISSUE TITLE
Logo for python-semver

### ISSUE THREAD

**Issue by scls19fr** [python-semver/python-semver#187]
As discussed in https://github.com/python-semver/python-semver/issues/177#issuecomment-549307654 a logo for python-semver is required.

Logo should be visible in https://github.com/python-semver/ and be [our visual identity in documentation](https://github.com/python-semver/python-semver/pull/185#issuecomment-552177934).

**Comment by tomschr** [comment]
Just for the records: of course, the logo that I've created isn't really fancy nor beautiful. If anybody have an idea to improve it, feel free to create a new PR. Thanks! :+1:

**Comment by scls19fr** [comment]
We can probably also add logo to README.md

**Comment by tomschr** [comment]
Hmn... :thinking:  For the time being, my personal opinion is *not* to include the logo into the README. The logo doesn't give a lot of information nor does it looks beautiful. It was a quick and dirty "design hack". :wink: 

Especially if you build the documentation and open the "Quickstart" page (the README) you will see two logos:

![logo-in-readme](https://user-images.githubusercontent.com/1312925/68757112-ac19cb80-060b-11ea-93bc-9ea00bdddca5.png)

So been there, done that. :wink: I think, we should avoid that. Less is more. :-)

**Comment by scls19fr** [comment]
I didn't anticipated the double logo issue.
Thanks. So let's close
