### ISSUE TITLE
Create Man Page for pysemver

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#191]
## Situation

When creating packages for Linux distributions (RPM or DEB), it is good practice to have a man page for each executable.

However, we currently don't have a dedicated man page for our `pysemver` script. Although we have rudimentary descriptions in our  `cli.rst`, it doesn't follow the man page style. 

## Proposed Solution

We should provide the man page for this project. When I've wrote this  `cli.rst` file, I didn't think of creating a man page. I better should have thought about that.

As such, I would suggest to improve the existing `cli.rst` page and turn it into a "real" man page. As we probably add more features in the future, we should prepare it to help users and packages.

I would propose to change the existing `cli.rst` file and add the usual man page structure:

```
NAME
    pysemver - Helper script for Semantic Versioning

SYNOPSIS
   pysemver compare version1 version2
   pysemver bump {major,minor,patch,prerelease,build} version

DESCRIPTION
   [...]
SEE ALSO
   https://python-semver.readthedocs.io/en/latest/

AUTHOR
   [...]
```

This can easily built with `sphinx-build` and choosing a man builder. After the man page was built, it can be added to the RPM or Debian package.

**Comment by scls19fr** [comment]
Good idea... even if 

    pysemver --help

should probably be enough for most of us.

**Comment by tomschr** [comment]
> should probably be enough for most of us.

I know, me included. :wink:  

When I've opened that issue, I had two target groups in my mind: packagers and contributors.

When I've tried to update the semver package for openSUSE, the build system gave me a warning message about a missing manpage. I don't know how other distributions deal with this, but in the worst case, it could fail to create the package. To avoid that, I think we should support those packagers.

That is one part. The other part are contributors. 

I assume, when semver includes more features through the pysemver CLI interface, they also need to be documented. With this issue, we create the foundation to allow this. So it's easier for contributors to add additional commands, options etc.

Additionally, we can include some background information into the manpage which wouldn't be common when displaying the `--help` output.

**Comment by ppkt** [comment]
I think it's a nice addition, especially for CLI tool, to have man page (I usually jump right into Examples section to check features)

btw. since we are talking about Linux distros - it seems that, at least in Debian / Ubuntu, there is quite old version of python-semver - 2.0.1. Maybe we should ask them to upload newer version?

**Comment by scls19fr** [comment]
Maybe we should have a look to see who is the maintainer of this Debian package.
Distributing python-semver as package for some Linux distros should be considered.
Maybe we should only consider for now Debian and Suse.

**Comment by tomschr** [comment]
Unfortunately, I don't know much about Debian packaging.

> Distributing python-semver as package for some Linux distros should be considered.
Maybe we should only consider for now Debian and Suse.

Good idea, that inspired me to another idea: why not extend the "Installing semver" section in our documentation? We could add where to get your package for your specific distribution and how to install it (via `apt-get`, `dnf`, or `zypper`).

By the way, you probably mean openSUSE. :wink:
