### ISSUE TITLE
Treat blank major/minor/patch/build values as zero

### ISSUE THREAD

**Issue by mcandre** [python-semver/python-semver#216]
Please treat missing major, minor, patch, and/or build values as zero. A great number of real world version numbers behave this way, e.g. `2`

**Comment by scls19fr** [comment]
Hi @mcandre 

You should have a look at https://python-semver.readthedocs.io/en/latest/usage.html#dealing-with-invalid-versions

Kind regards

**Comment by tomschr** [comment]
Hi @mcandre
Thanks for your ideas, much appreciated. 👍
Does the link help?

We try to follow the semver specification very close. This means, unfortunately, that in some cases we need to reject issues which are not compatible with the spec. That's the case here, I'm sorry.

@scls19fr I think we can close this bug as invalid.
