### ISSUE TITLE
Create native coercion of C#/MS style 'semver' format x.y.z.a

### ISSUE THREAD

**Issue by kenneaal** [python-semver/python-semver#220]
Numerous C#/.NET Core projects  use a major.minor.revision.build format, which closely emulates semver. python-semver correctly rejects these as non-valid semver strings, and one is left coercing the version into a semver format. (Thus my need for .isvalid() in previous issue)

Would it be possible to add a flag to semver's parser methods like _coerce=True_ to have it attempt to glean a semver number by chopping off excess bits?

**Comment by scls19fr** [comment]
Looks quite similar to #210

**Comment by tomschr** [comment]
@kenneaal Hi Kenneth, thanks for your issue.

I had this idea also in my mind, but we've agreed to document it in our documentation and not integrating it into the library. See the respective issue #210 for details.

You may find this little section useful:
https://python-semver.readthedocs.io/en/latest/usage.html#dealing-with-invalid-versions
