### ISSUE TITLE
Decide to deprecate module level functions?

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#225]
## Situation

Currently, we have mostly functions which are either on the module level (`semver.next_version`, `semver.bump_*`) and almost the same on the `VersionInfo` level (`semver.VersionInfo.next_version`, `semver.VersionInfo.bump_*`).

I know, they both serve distinctive purposes: the first expects and returns a string whereas the second needs a `VersionInfo` object.

However, from an implementation perspective, I'm wondering if this is double work. It looks inefficient to me when the `VersionInfo` methods need to convert the object first into a string, call the modul level function, and convert it back to a `VersionInfo` object.

IMHO, we should improve this situation.

## Suggested Solution

The question boils down to this: should we treat `VersionInfo` as **first class object**?

I have the impression this isn't currently the case. The developer can decide between two implementation which does mostly the same. The only difference is, one implementation use strings, the other use a "detour" with an `VersionInfo` object.

If we would treat `VersionInfo` as our one and only solution, that would mean we have to move the implementation into the methods. The module level functions would serve as "helper functions".

Or... maybe we could think about a more radical approach? Are the module level functions really necessary? Should we deprecate them? As we can convert a `VersionInfo` object into a string through `str(versionobject)`, it seems to me, they are obsolete...

I see the following benefits of this approach:

* Focus on the `VersionInfo` class, all the magic would happen there. :wink: 
* Avoids writing two functions which mostly implements the same functionality, but with different types.
* Simplifies testing.
* Focus more on objects than strings (which can't be controlled).
* Improves the project to be more slim and well-arranged.
* Makes conversion between objects obsolete. Without conversion, it would have a improved effect on performance (maybe only slightly, but...).

If we want to follow this path, we would need:

* Use the `warning` module to issue a deprecation warning in affected module functions.
* Document the change for our upcoming major release. :wink:
* Release 2.9.2 of semver to implement the warnings
* Make the whole removal in release 3 only.

@gsakkis, @scls19fr  Does that make sense to you? Do I miss an important point? I would really like to hear your view on this. :heart:

**Comment by gsakkis** [comment]
@tomschr I fully agree on deprecating and eventually removing the module level functions :+1:

**Comment by scls19fr** [comment]
Removing functions on module level can only be done with major version upgrade (to respect semver). A first step could be to deprecate if there is a general consensus

**Comment by tomschr** [comment]
Maybe I want clear, but if course I meant it to remove them only in a major release. If nobody objects. ;))

**Comment by tomschr** [comment]
Just to clarify the pull request #229: it doesn't remove the modul level function, it lays the foundation so we can remove them easily once we work on major release 3.

**Comment by ppkt** [comment]
@tomschr I've mixed feelings about this - while I agree with your points (especially about duplicated code) - I think we should allow using semver in both ways because a lot of software is using module level functions currently. 
I checked some popular tools which are using semver: https://libraries.io/pypi/semver/usage:
 - [mozilla/DeepSpeech](https://github.com/mozilla/DeepSpeech/blob/87f70693c381e3c5cf8f7024798f2487d1ba6b4f/util/helpers.py#L53)
 - [getredash/redash](https://github.com/getredash/redash/blob/2dff8b9a00d23ef6f7a2d108c8560ec38f8f8960/redash/version_check.py#L107)
- [StackStorm/st2](https://github.com/StackStorm/st2/blob/9edc3fb6da7f12515f6011960f1b72538e53368e/st2common/st2common/expressions/functions/version.py)

Enforcing OOP it in next major version is completely fine, but maybe it'll be better to put some extra effort and maintain support for current "users" of module level functions? :)

**Comment by tomschr** [comment]
@ppkt Thanks Karl for your feedback, much appreciated! :+1: 

> we should allow using semver in both ways because a lot of software is using module level functions currently.

This is still the case with the current version. For 2.9.x, it won't change, they will be available. The only difference against previous versions are that the user get a deprecation warning message to use other functions.

Or do you talk about the next major release?

> I checked some popular tools which are using semver: https://libraries.io/pypi/semver/usage:

I didn't know that Web page. Very cool, thanks for the link! :+1: 

> maybe it'll be better to put some extra effort and maintain support for current "users" of module level functions? :)

Ok, could you be a bit more verbose what you had in your mind?

**Comment by ppkt** [comment]
Sorry, wasn't clear enough :)

My point is - a lot of software is currently using "module level functions" - by deprecating them (and removing) they might stay with 2.x version. Maybe it's better to refactor code to avoid duplication but leave both ways of working on versions (string-based and object oriented)?

**Comment by tomschr** [comment]
@ppkt Oh, I see what you mean. So we should keep them in your opinion. 

> My point is - a lot of software is currently using "module level functions" - by deprecating them (and removing) they might stay with 2.x version.

Yes, that's a valid point. I have to agree, I have mixed feelings. :wink: 

On one side, I can fully understand that developers don't want to change a running system. Even if the change would be minor.

On the other side, the change is not that difficult. Change is inevitable. Modules change, programs change, even big operating systems does that. :wink:  Of course, the change should be communicated, useful, and there should be a clear migration path.

So... one option could be, to still have the module level functions in place for major release 3, but with all the deprecation warnings. However, I would definitely remove them in major release 4. That should give people really enough time. Of course, it should also be covered by our documentation (I currently lack a good description, I'm aware of that, but haven't had the time).

What do you think of this idea?

**Comment by ppkt** [comment]
@tomschr I saw your comment in some other ticket and I completely agree with it - "there should be only one way to do it". I also noticed in your PR is detailed instruction how to replace deprecated functions and I think it's really great.

I also think we should stick with your initial proposal - to deprecate them in 2.9.x and remove in 3.x - there will be a lot of other, potentially breaking, changes in new version so someone who is using our library, will have to check documentation and fix all warnings and errors :)

**Comment by tomschr** [comment]
@ppkt Thanks Karol for your ideas. :+1: 

Yes, we have now documentation for it. :wink: I've tried to address this and help our users to "migrate". If you have any further ideas, suggestions, or found anything missing, please let me know so I can improve it.

Regarding your change, yes, sure, we can deprecate them in 2.9.x and remove in 3.x. :wink:  That's why we discuss this and try to find the best solution. 

Could you do me a favor and can do a short test in regards to https://github.com/python-semver/python-semver/pull/229#issuecomment-612371921? It's about the warning and it drives me nuts. :smile:  Maybe I need to read the documentation more carefully.

Thanks Karol! :+1:
