### ISSUE TITLE
Can't import VersionInfo in python3.7

### ISSUE THREAD

**Issue by syntroniks** [python-semver/python-semver#231]
To reproduce:
```
~> py --version
Python 3.7.6
~> pip3 install semver
Collecting semver
  Using cached semver-2.9.1-py2.py3-none-any.whl (9.8 kB)
Installing collected packages: semver
Successfully installed semver-2.9.1
~> py
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from semver import VersionInfo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'VersionInfo' from 'semver' (C:\Users\me\AppData\Local\Programs\Python\Python37\lib\site-packages\semver\__init__.py)
```
I've also tried it without the wheel by passing in --install-option="--no-compile" -- no luck.
semver works great for me in 32-bit python 2.7.

**Comment by syntroniks** [comment]
Upgraded from 
`Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32` 

to 
`Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)] on win32`

and all is well. Why could this be?

**Comment by tomschr** [comment]
Thanks @syntroniks for your report. :+1: 

However, this one looks suspicious:

```
> >>> from semver import VersionInfo
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: cannot import name 'VersionInfo' from 'semver' (C:\Users\me\AppData\Local\Programs\Python\Python37\lib\site-packages\semver\__init__.py)
```

The current semver library doesn't have an `__init__.py` file, only `semver.py`. So this must be something else, maybe a different library with the same name?

Can you check what this file contains?

**Comment by tomschr** [comment]
> Upgraded from
> `Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32` (installed per-user)
> 
> to
> `Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)] on win32` (installed for all users)
> 
> and all is well. Why could this be?

The first version is 64bit, the second one 32 bit. Plus it's a different version. I'm not sure how the Python version is installed under Windows, but I guess, both are located in different directories.

**Comment by syntroniks** [comment]
I think that somehow I received this file
https://github.com/podhmo/python-semver/blob/89667077eada74eb348cf5ecfa7563f40fdbf544/semver/__init__.py

While `semver-2.9.1-py2.py3-none-any.whl` came from this (python-semver) project, I suppose it could be that either pip, my interpreter, or environment were preferring this file that is not associated with python-semver.

I think at this point, it isn't actionable for the python-semver maintainers. You can close this if you agree.
Thanks for your quick response!

**Comment by tomschr** [comment]
I see. Thanks for your debugging. Much appreciated! :+1: 

Good that we haven't switched to a semver packaging yet. :wink: Ok, I'll close this bug then.

Thanks and stay healthy.
