### ISSUE TITLE
VersionInfo.next_version() returns Union[VersionInfo, str]

### ISSUE THREAD

**Issue by tlaferriere** [python-semver/python-semver#251]
`VersionInfo.next_version()` return type is uncertain because at line 463 of semver.py `return version.replace(prerelease=None, build=None)` returns a VersionInfo object, whereas in line 466 it is explicitly converted to `str` and at line 470, `version.bump_prerelease()` is documented with `rtype: str`.  
This is problematic because if you call this on a version that has a prerelease or build number, you get a `VersionInfo` object, and otherwise you get a `str`, and these two types must be handled quite differently.

Personally, I would expect `VersionInfo.next_version()` to return a `VersionInfo` object in all cases, but I think the main problem here is the ambiguity of the return type.

**Comment by tomschr** [comment]
Thanks @tlaferriere for your report! I think this is an oversight. From my understanding, the method should always return a VersionInfo object.

We should ask @gsakkis, I guess you've intended to return a VersionInfo object all the time, am I right with this assumption?

**Comment by tomschr** [comment]
Thanks George for conforming! :+1:

I will create a 2.10.1 release soon.
