### ISSUE TITLE
next_version(""prerelease") does not bump patch when prerelease exists

### ISSUE THREAD

**Issue by baderj** [python-semver/python-semver#280]
``str(semver.VersionInfo.parse("0.1.4").next_version("prerelease"))`` returns ``0.1.5-rc1`` as expected. However, 

``str(semver.VersionInfo.parse("0.1.4").next_version("prerelease").next_version("prerelease"))`` returns ``0.1.5-rc2`` instead of ``0.1.6-rc2``.

**Comment by tlaferriere** [comment]
This seems like the right behaviour. When you want the next prerelease version of a prerelease, you get a simple prerelease bump. A patch bump only occurs when there isn't a prerelease yet, as it doesn't make sense create a prerelease *after* a release.
Hope I was of some help 😀

**Comment by tomschr** [comment]
Thanks Johannes for you report and Thomas for your comment. :+1: 

I think, we can close this issue as @tlaferriere already gave a good explanation. Thank you Thomas!
@baderj Johannes, if you disagree or if you have think we missed something, please reopen it. Thanks! :+1:

**Comment by baderj** [comment]
Makes perfect sense, Thank you.

**Comment by tomschr** [comment]
@baderj I forgot to add: you can have this behaviour with the following code: 

```python
>>> semver.VersionInfo.parse("0.1.4").bump_patch().next_version("prerelease").next_version("prerelease")                                          
VersionInfo(major=0, minor=1, patch=6, prerelease='rc.2', build=None)
```

Which might or might not what you wanted. :wink: 

Also compare https://python-semver.readthedocs.io/en/latest/usage.html#raising-parts-of-a-version
