### ISSUE TITLE
Add support for PyPI pre-releasing semver format.

### ISSUE THREAD

**Issue by hadialqattan** [python-semver/python-semver#281]
I know PyPI preleases semver isn't a valid v2.0, but it would be great if we have a method that converts it to a valid semver and validating it as a valid semver!

Example of PyPI prelease semver: 
```semver
0.0.1a3
```
Which means:
```semver
0.0.1-alpha.3
```

**Comment by tlaferriere** [comment]
I agree, I think this would make this a lot more practical. I think this also has to do with the wider concept of formatting the versions and parsing them. Maybe revamping the formatting and parsing could be a goal of the upcoming v3, @tomschr ?

**Comment by tomschr** [comment]
Yes, we could think about adding such a feature. I would suggest to add that for the semver 3 release line.

**Comment by tomschr** [comment]
@hadialqattan After thinking about a bit more, how should this exactly work?

We could (theoretically) create a function/method etc. to massage the string `0.0.1a3` and convert it into `0.0.1-a3`. That would probably be feasible. However, I'm not so sure about converting `0.0.1a3` into `0.0.1-alpha3`. Wouldn't that change its semantic? Are you really absolutely sure, that "a" means _always_ "alpha"?

**Comment by hadialqattan** [comment]
> @hadialqattan After thinking about a bit more, how should this exactly work?
> 
> We could (theoretically) create a function/method etc. to massage the string `0.0.1a3` and convert it into `0.0.1-a3`. That would probably be feasible.
> 
> However, I'm not so sure about converting `0.0.1a3` into `0.0.1-alpha3`. Wouldn't that change its semantic? Are you really absolutely sure, that "a" means _always_ "alpha"?
> 
> If I'm not mistaken, PyPI implements [PEP 0440](https://www.python.org/dev/peps/pep-0440/), right?

Yeah, you're right, but I'm sure `a` means `alpha` and `b` means `beta`.

Anyway, your solution is better than mine.

**Comment by tomschr** [comment]
Just as an addendum: I've created a section in the documentation to convert from PyPI versions to semver (and vice versa). Find more information at https://python-semver.readthedocs.io/en/latest/advanced/convert-pypi-to-semver.html

**Comment by tomschr** [comment]
Seems this is already implemented so I close it. Thanks!
