### ISSUE TITLE
Get the community active again

### ISSUE THREAD

**Issue by tlaferriere** [python-semver/python-semver#282]
It has been awfully quiet around here for a while. @tomschr you were the last active maintainer I have interacted with on this project. Maybe starting a gitter community for this project would help? It would give us a place to connect and banter, while keeping the serious work here in the issues.

**Comment by tomschr** [comment]
@tlaferriere Thank you Thomas. I'm sorry, but I was busy with other things and couldn't take care of that. However, I haven't completely forgot it. So I hope all my issues are settled now and I've planned to contribute to this project more in the upcoming weeks and months.

Thanks for your ideas. I haven't used Gitter. Did you? :wink:

**Comment by tlaferriere** [comment]
Not really. But I have seen it used on other projects. The website also says it is totally free, and it has integration with GitHub. I'll try creating a community and linking it here

**Comment by tlaferriere** [comment]
Actually a gitter community can be created for an org, but I can't create one for the python-semver org. <https://gitter.im/home/explore#createcommunity> @tomschr you should be able to link it since you're a part of the org

**Comment by tomschr** [comment]
I've tried to add the OAuth application Gitter Public Repo Access to python-semver, but it seems I have insuffient right. :thinking: Didn't see any mails at all.

**Comment by tlaferriere** [comment]
This [article](https://gitlab.com/gitlab-org/gitter/webapp/blob/develop/docs/faq.md#why-isnt-my-github-organisation-or-repos-appearing) has some troubleshooting info

**Comment by tomschr** [comment]
At least, we have now a new 2.11.0 release: https://github.com/python-semver/python-semver/releases/tag/2.11.0 ! :tada:

**Comment by tomschr** [comment]
Now, the latest 3.0.0-dev.1 is out of the door. :tada: 
After the release is before the (next) release. So we should think about what should we integrate into 3.0.0-dev.2.

@tlaferriere Any ideas/suggestions/wishes?

I plan to add a short section about substantial differences from the user's perspective.

**Comment by tlaferriere** [comment]
ATM I'm working on splitting up the code in a package. You'll see the PR soon. Otherwise I had started experimenting with parsing in hopes of making it more powerful (configurable and flexible). It's quite chunky, so it might require a few iterations.

**Comment by tomschr** [comment]
@tlaferriere I've created a [Gitter community](https://gitter.im/python-semver-python-semver/) and added you. :wink: Just trying to find out. Any further suggestions?

**Comment by tlaferriere** [comment]
I think that's sorted now 🎉
