### ISSUE TITLE
Support suffix 'v'

### ISSUE THREAD

**Issue by xtuchyna** [python-semver/python-semver#285]
While browsing repositories on Github, I've noticed that often the suffix 'v' is used within semantic versioning (althought the `semver.org` does not have any specification for this).

One of the example is tensorflow, where it is explicitly mentioned that they use semantic versioning (https://www.tensorflow.org/guide/versions). However, in tags every version is suffixed so it looks like vX.Y.Z.

When passing this string to VersionInfo parser, it is rejected

<pre><code>
semver.VersionInfo.parse('v2.3.1')
Traceback (most recent call last):
  ...
/python3.6/site-packages/semver.py", line 656, in parse
    raise ValueError("%s is not valid SemVer string" % version)
ValueError: v2.3.1 is not valid SemVer string
</code></pre>

So, should it be considered for support?

**Comment by xtuchyna** [comment]
yes, the documentation is enough!

Thank you.

**Comment by tomschr** [comment]
@xtuchyna Dominik, the latest release contains an additional small section about subclassing VersionInfo which may also related to your use case. Check it out here:

https://python-semver.readthedocs.io/en/latest/usage.html#creating-subclasses-from-versioninfo

Hope it could help you. :-)

**Comment by xtuchyna** [comment]
yes, nice and handy :) thxx
