### ISSUE TITLE
semver.VersionInfo allows negative numbers

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#291]
# Situation

If you pass negative numbers into `semver.VersionInfo` it doesn't raise any errors:

```python
>>> import semver
>>> semver.VersionInfo(-2)                                                                                                                           
VersionInfo(major=-2, minor=0, patch=0, prerelease=None, build=None)
```

Tested with latest 2.11.0

# Proposal

I guess, this shouldn't happen. We should raise a ValueError exception.
Would integrate that into a 2.12.0 release and into the upcoming 3.0.0-alpha0.

@tlaferriere Thomas, can you conform? Do you agree?

**Comment by tlaferriere** [comment]
I agree. It is doesn't make sense to have negative version numbers, whichever way you put it.

**Comment by scls19fr** [comment]
Hi all,

according to https://semver.org/

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, ...

So according spec, negative integers are not allowed.

**Comment by tomschr** [comment]
Thanks to both of you for confirming. It's surprising that this bug could survive that long. :smile:
