### ISSUE TITLE
Create for semver 3.0.0-dev2

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#302]
# Situation

As 3.0.0-dev.1 is just released, we should think about to coordinate the next development release.

# Suggested Plan

I have a couple of ideas in mind, but would like to hear from others:

* ~Maybe switching to a `src` layout; in regards to this we could think about #169~ done
* ~Doc: I plan to add a short section about substantial differences from the user's perspective.~ done
* Should we consider #248? Is it worth the effort? -> something for dev.3
* We also need to be decide about #258  -> something for dev.3?

Just some ideas, nothing in particular order.

**Comment by tlaferriere** [comment]
I created issue #305 and I've addressed it in #304.

**Comment by tomschr** [comment]
This is done with https://github.com/python-semver/python-semver/releases/tag/3.0.0-dev.2
