### ISSUE TITLE
Should _comparator return NotImplemented instead of raising TypeError?

### ISSUE THREAD

**Issue by tomschr** [python-semver/python-semver#316]
# Situation

when comparing an incompatible type, the `Version` class raises `TypeError` (through the `_comparator` decorator):

```python
>>> class Foo:
...    pass

>>> v1 = semver.version.Version(1, 2, 3)
>>> v1 < Foo()
Traceback (most recent call last)
...
TypeError: other type <class '__main__.Foo'> must be in (<class 'semver.version.Version'>, <class 'dict'>, <class 'tuple'>, <class 'list'>, <class 'str'>, <class 'bytes'>)
```

From a semantic point of view this is correct.

# Question

According to the [NotImplemented](https://docs.python.org/3/library/constants.html#NotImplemented) documentation (emphasize by me):

> Special value which should be returned by the binary special methods (e.g. `__eq__()`, `__lt__()`, `__add__()`, `__rsub__()`, etc.) to indicate **that the operation is not implemented with respect to the other type**; may be returned by the in-place binary special methods (e.g. `__imul__()`,` __iand__()`, etc.) for the same purpose. It should not be evaluated in a boolean context.

Should we return `NotImplemented` instead of raising `TypeError`?

@python-semver/reviewers @tlaferriere Thoughts? Concerns?

**Comment by tlaferriere** [comment]
I think this would make sense since this function is meant to be used in the `__gt__` magic method and family. I also don't see much of a problem changing this because we're making it private.

Sounds good to me overall.
