### ISSUE TITLE
SemVer not parsing major.minor version strings as seen in `pip list`

### ISSUE THREAD

**Issue by PompeiaPaetenari** [python-semver/python-semver#328]
# Situation
Attempting to use SemVer to process the `pip list` results and getting errors for packages that have only the major and minor version specified, as follows:
`promise           2.3`

# To Reproduce
```python
>>> VersionInfo.parse('2.3')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/Library/Python/3.9/lib/python/site-packages/semver.py", line 726, in parse
    raise ValueError("%s is not valid SemVer string" % version)
ValueError: 2.3 is not valid SemVer string
>>> VersionInfo('0.1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/Library/Python/3.9/lib/python/site-packages/semver.py", line 254, in __init__
    value = int(value)
ValueError: invalid literal for int() with base 10: '0.1'
```

# Expected Behaviour
An object should be returned with a patch value of zero:
`VersionInfo(major=2, minor=3, patch=0, prerelease=None, build=None)`

# Environment
- OS: MacOS 10.15.7
- Python version: 3.9
- Version of semver library: `semver            2.13.0`
I also tried using `version.py` from the latest master.

# Additional context
My understanding from skimming the code is that `class Version` has an init which handles this, providing default values of `0` where they are not provided, but this does not seem to be occurring.

**Comment by tomschr** [comment]
Thank you @PompeiaPaetenari for your report. Much appreciated! :+1: 

Well, according to the semver specification, the string "2.3" is not a valid semver string unfortunately. The exception message `ValueError: 2.3 is not valid SemVer string` is correct here. This is not a bug, the library adheres to the specification.

For your second call, the call `VersionInfo('0.1')` is invalid in semver 2.13.0, see https://python-semver.readthedocs.io/en/2.13.0/usage.html#creating-a-version. Only integers are allowed to call the class. For semver 2.13.0, you can use `VersionInfo.parse` to pass a string.

However, we are currently discussing this for `VersionInfo()` to lift the arguments for the upcoming 3.0.0 and allow strings too. The discussion hasn't been finished yet.

For your problem there is already a solution: you can try the `coerce` function from the section [Dealing with Invalid Versions](https://python-semver.readthedocs.io/en/2.13.0/usage.html#dealing-with-invalid-versions) of our documentation.

For the time being I'm setting this to resolved. If you still think there is something wrong, just reopen it and we can discuss this.

Thanks!
