### ISSUE TITLE
version file open method

### ISSUE THREAD

**Issue by curtisma** [python-semver/python-semver#340]
# Situation

I would like to have a simple text file in my repo, named "version", which contains only the semantic version number of the project.  This could then be consumed by every place in the code that needs to know the package number.   

For example, I may need it for the __version__ attribute of the package, again for the documentation, and again for the Pip or [Conda ](https://docs.conda.io/en/latest/) packaging configuration.  Having all these share a single, simple source for the version number would make it easy to update the version number.  It would also make it easy to get the version number for tools and packages written in other languages since it is stored as a simple text file that almost all languages can read.  Especially since you have a CLI that would make it easy to use with other languages also.

# Possible Solution/Idea

I propose adding a static or class method "open" which takes a string or path object pointing to the version file.  The version file will only contain the semantic version.  The method will read in the file and return a Version object.

# Additional context
While it seems easy enough to open the file and pass it to the Version constructor as a string, this would require adding scripts or modules to each project to add this basic functionality.  Python is all about "batteries included", right?

**Comment by tomschr** [comment]
Thanks @curtisma for your idea!

I'm not sure if this specific use case is appropriate for the `Version` class. It sounds a bit too special for my taste. I would prefer to keep the class as small as possible.

From my gut feelings, this would be an example of a customization by a user. I'd add it to the documentation of how to customize the class.

However, that's my taste and I could be wrong. Maybe you have some convincing arguments why this could be useful for more people?

@tlaferriere What do you think?

**Comment by curtisma** [comment]
Awesome, thanks!
