### ISSUE TITLE
A more flexible matching rule

### ISSUE THREAD

**Issue by llbai** [python-semver/python-semver#345]
# Situation

I hope I can in my python project, more succinctly and more advanced compare versions

# Possible Solution/Idea

A more flexible matching rule, like node-semver's Advanced Range Syntax
eg:
* Hyphen Ranges X.Y.Z - A.B.C
* X-Ranges 1.2.x 1.X 1.2.* *
* Caret Ranges ^1.2.3 ^0.2.5 ^0.0.4
* ...

# Additional context

**Comment by tomschr** [comment]
Thanks @llbai for your report! Much appreciated. :+1: 

Your suggestion is already covered in #241. Closing this as a duplicate.
