### ISSUE TITLE
The type of the “parts” argument of VersionInfo.replace is incorrectly inferred by PyCharm

### ISSUE THREAD

**Issue by FabienSailliet** [python-semver/python-semver#357]
# Situation

When calling the method `VersionInfo.replace()` with named parameters, PyCharm shows a warning indicating that the parameters that I am giving are not of the right type.

# To Reproduce

Paste the following code in PyCharm:
```python
version = VersionInfo.parse("1.0.0")
alpha_version = version.replace(
    prebuild="alpha"
)
```

# Expected Behavior

PyCharm will show the error `Expected type 'dict', got 'str' instead` as follows:
![image](https://user-images.githubusercontent.com/49949519/156781546-ab8e3936-8ad8-4e5c-9c1c-4c414fbf1ce4.png)

# Environment
- OS: Kubuntu 20.04
- Python version: 3.8
- Version of semver library: 2.13.0

# Additional context

The source of the issue is that PyCharm infers that the `parts` argument is a dict of dict, as can be seen in the following screenshot:
![image](https://user-images.githubusercontent.com/49949519/156782230-b0ddb1f1-c21d-4cc9-85ce-77f19b3f7592.png)

**Comment by FabienSailliet** [comment]
The issue can be fixed by changing the definition of the method `VersionInfo.replace()` from that:

```python
def replace(self, **parts):
```

To that:

```python
def replace(self, **parts: str):
```

**Comment by tomschr** [comment]
Ahh, thank you @FabienSailliet for your report! Much appreciated. :heart: I will look into this.

**Comment by tomschr** [comment]
After playing a bit, `str` isn't enough. As some parts can be of type `str`, `int`, or even `None`, we need to extend the signature:

```python
def replace(self, **parts: Union[str, int, None]) -> Version:
    # ...
```

**Comment by FabienSailliet** [comment]
Thank you for your quick answer. You're right, I was only only thinking about my use case.

**Comment by tomschr** [comment]
Okay, after dig into the code, the change is already there in master. See https://github.com/python-semver/python-semver/blob/master/src/semver/version.py#L586:

```python
def replace(self, **parts: Union[int, Optional[str]]) -> "Version":
```

Basically the same. :wink: If you don't mind, I'd close this issue. :slightly_smiling_face:

**Comment by tomschr** [comment]
Argh, I should have better read your issue, sorry. You are talking about version 2.13.0!

This version is _frozen_ and won't receive any updates, unfortunately. That version does not contain any type hints at all. 

We focus entirely on the upcoming major 3 release. You should make sure to update your code and use it once it is released.

**Comment by FabienSailliet** [comment]
Ho, ok. I prefer to stay on a stable version, but I'm for sure looking forward to the next version! I let you close the issue if you want to.

**Comment by tomschr** [comment]
Ok, thanks. In that case, I'd prefer to close it a it's already implemented in the development version.

Thanks for your contribution. 👍
