### ISSUE TITLE
README.md file example need to updated gives `attributeError: module 'semver' has no attribute 'Version'`

### ISSUE THREAD

**Issue by slayer321** [python-semver/python-semver#381]
# Situation

README.md file needs to be updated as now we have `semver.VersionInfo.parse('1.2.3-pre.2+build.4')`  class(VersionInfo) name instead of the older one(Version) that is mentioned in the README
# To Reproduce
When running the command mentioned in the README `ver = semver.Version.parse('1.2.3-pre.2+build.4')` it gives below error
`AttributeError: module 'semver' has no attribute 'Version'`

# Expected Behavior

If we use correct class name it works fine

# Environment
- OS: [e.g. Linux, MacOS, Windows, ...]
- Python version [e.g. 3.6, 3.7, ...]
- Version of semver library [e.g. 3.0.0]

# Additional context

**Comment by tomschr** [comment]
Thanks @slayer321 for your report and welcome! :wave:

I'm not sure if I understand your issue. The current master branch contains the development version of this project (currently 2.0.0-dev.3).

The class `VersionInfo` was the _old_ name; it has been renamed to `Version`. Regardless of the name change, there is still an [alias VersionInfo available](https://github.com/python-semver/python-semver/blob/master/src/semver/version.py#L666).

Here is a small session that use both:

```shell
$ PYTHONPATH=src python3 -c "import semver; print(semver.VersionInfo.parse('1.2.3-pre.2+build.4'))"
1.2.3-pre.2+build.4
$ PYTHONPATH=src python3 -c "import semver; print(semver.Version.parse('1.2.3-pre.2+build.4'))"
1.2.3-pre.2+build.4
```

Can you elaborate? :slightly_smiling_face:  Are you using still the old version 2?

**Comment by slayer321** [comment]
yes, I check I'm still using semver 2 .. Will close this issue

**Comment by tomschr** [comment]
No problem. Thanks for your contribution anyway. If you observe anything else, don't hesitate and open a issue.

**Comment by spoorcc** [comment]
For whomever it may be useful, I ran into a similar issue, but this was due to a package bringing in [`poetry-semver` ](https://github.com/python-poetry/semver). This is also called `semver` and had me scratching my head for a while before figuring out.

**Comment by tomschr** [comment]
> For whomever it may be useful, I ran into a similar issue, but this was due to a package bringing in [`poetry-semver` ](https://github.com/python-poetry/semver). This is also called `semver` and had me scratching my head for a while before figuring out.

Thanks for the comment @spoorcc! We have the similar issue #259. Unfortunately, the name "semver" is a very common. I'm not sure how to solve this as PyPI allows libraries of the same name.

Regarding the python-semver: the GitHub project is archived. It seems, it was done as the project isn't maintained anymore. The last commit was 3 years ago. Maybe a good opportunity to migrate to this project? :wink:

**Comment by spoorcc** [comment]
Thanks for the reply @tomschr!

I'm already a big fan of your package 😉! I use it in https://github.com/dfetch-org/dfetch.

In my case a sub-sub dev-dependency started using `poetry-semver` unfortunately 😢. This caused pylint to start complaining which brought me to this issue. [prospector](https://github.com/PyCQA/prospector) --> [requirements-detector](https://github.com/landscapeio/requirements-detector) --> `poetry-semver`

I've opened an issue in the requirements-detector repository to replace `poetry-semver` with `semver` (https://github.com/landscapeio/requirements-detector/issues/40) maybe I can create a new fan :wink:.

**Comment by tomschr** [comment]
Thanks Ben/@spoorcc! Oh, that's really nice, thank you!

Ahh yes, naming things can be really tricky. I'm sorry for your issues. I thought about renaming the package, but wasn't sure if that wouldn't cause more problems than it solved.

Thanks for opening the new issue. :+1:  Hope they can migrate it to this project. :wink:

All the best and if you have further ideas, comments, bug fixes etc. let us know.
