### ISSUE TITLE
Feature request: support `pyproject.toml` version strings

### ISSUE THREAD

**Issue by bersbersbers** [python-semver/python-semver#391]
Python version strings, at least as defined in `pyproject.toml` files, use something to the sort of `[N!]N(.N)*[{a|b|rc}N][.postN][.devN]`.

# Situation
```python
>>> semver.Version.parse("1.2.3.4")                                  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\vers\.pyenv-win-venv\envs\project\Lib\site-packages\semver\version.py", line 608, in parse
    raise ValueError(f"{version} is not valid SemVer string")
ValueError: 1.2.3.4 is not valid SemVer string
```

# Possible Solution/Idea
Support more (all?) possible Python version strings.

# Additional context
- See https://python-poetry.org/docs/pyproject/#version
- See https://peps.python.org/pep-0440/#public-version-identifiers (PEP 440)
- Compare https://github.com/python-semver/python-semver/issues/284

**Comment by tomschr** [comment]
Hi @bersbersbers, :wave: 

thanks for your bug report, much appreciated! :+1: 

Your request goes beyond what the semver spec and this library supports. Python version strings are unfortunately not fully semver compatible. This is the bad news.

The good news is that to some degree it's possible to convert from one version spec to the other. I covered this already in the section [Converting versions between PyPI and semver](https://python-semver.readthedocs.io/en/latest/advanced/convert-pypi-to-semver.html). The documentation mentions explicitly PEP 440.

If something is not covered in the documentation, I'm more than happy to amend the text. However, adding support for PEP440 into the library is out of scope.

Is the above documentation sufficient for your use case?

**Comment by bersbersbers** [comment]
This is great, thank you!

Sorry for opening this without any need - I had searched for PEP 440 in the issue without finding anything, yet had not checked out the docs before. I guess other people doing the same will now at at least find this very issue ;)

**Comment by tomschr** [comment]
Don't worry, this is absolutely no problem. :slightly_smiling_face: Thanks for commenting.

Yes, there was a similar feature request some time ago. Seems I need to advertise the docs more prominently. :wink:
