### ISSUE TITLE
Parse PEP440 versions

### ISSUE THREAD

**Issue by david-waterworth** [python-semver/python-semver#395]
I've setup my package to use `setuptools_scm` to dynamically generate the version from git tags.

The problem I'm encountering is when the latest tag says `0.2.0` and the repo contains at least one commit since the tag, `setuptools_scm` assigns a version of `0.2.1.dev6+g8dc9921.d20230224`

From what I understand `setuptools_scm` produces [PEP 440](https://www.python.org/dev/peps/pep-0440/#version-scheme) compliant version numbers, which are not always compatible with SemVer. So in this case for example `semver` raises an exception

ValueError: 0.2.1.dev6+g8dc9921.d20230224 is not valid SemVer string

I've been unable to find a maintained package that supports PEP 440 so it would be a nice addition (although quite possibly outside your scope) to include different models (strict SemVer, PEP 440 etc)

**Comment by tomschr** [comment]
Hi @david-waterworth,
thanks for your contribution!

You are not the first one that has this issue. :wink: Yes, that's really unfortunate. Semver is pretty clear about what's valid and what's not. As you already found out, you can't really convert between setuptools_scm versions and semver.

Have you read the documentation about [Converting versions between PyPI and semver](https://python-semver.readthedocs.io/en/latest/advanced/convert-pypi-to-semver.html)? The covers exactly PEP 440 compliant version numbers and how to convert them. I would assume this is what you are looking for. If not, I'd happy to discuss your suggestions. :wink:

As you already assumed, it's out of scope of this project. However, that doesn't mean we cannot improve the documentation. If you have an idea about how to amend the text that would be great!

Would that help?

**Comment by david-waterworth** [comment]
Thanks - I wasn't aware of 'packaging.version' so that's super helpful. I just want to pear out whether the version is a dev, staging (rc) or prod release so I think the documentation you linked covers that.

**Comment by tomschr** [comment]
Great! Thanks for your answer.

If you don't have any other issues, I'm closing this issue. Reopen it if you would like to see some additions in the documentation.

Many thanks! Wish you a successful work with semver. :slightly_smiling_face:
