### ISSUE TITLE
Module "semver" does not explicitly export attribute "Version"

### ISSUE THREAD

**Issue by Soneji** [python-semver/python-semver#410]
Hi

I am running `mypy` the python static type checker in my project with the `--strict` flag and it is causing an error. 

```
Module "semver" does not explicitly export attribute "Version"
```

I have replicated the error in this repl environment online
https://replit.com/@soneji/semver-mypy

You can click "show code" to see the code but I have printed it also

I have followed the usage instructions in the documentation so I am unsure why this error is being caused

**Comment by tomschr** [comment]
Thank you @Soneji for your contribution. Much appreciated! :+1: 

Seems this is caused by a missing `__all__` variable.

It's strange that mypy doesn't detect it. When I run `tox -e mypy` this error doesn't show up.

**Comment by Soneji** [comment]
Maybe you need strict mode for mypy to detect it?

**Comment by tomschr** [comment]
> Happy to submit a PR, do you think you could publish a fixed version of the package after this?

Please do! Happy to include it.

> I notice you added some release tags to this issue, are you waiting on a particular set of features before publishing a new release?

That's just so I can find them. Nothing special to it. :wink:
I can release a 3.1.0 version if you need it.

> Maybe you need strict mode for mypy to detect it?

That was also my suspicion. I indeed tried the `--strict` option and it found also some issues. However, from what I could see, they are all unrelated to this specific issue.
