### ISSUE TITLE
Support version bump while perserving build metadata 

### ISSUE THREAD

**Issue by KCSesh** [python-semver/python-semver#415]
# Situation

Would like the ability to bump versions (major/minor/patch) while preserving my build metadata.

# Possible Solution/Idea

```
ver = semver.Version.parse('3.4.5+myMetadata')

ver.bump_patch(build=ver.build)
Version(major=3, minor=4, patch=6, prerelease=None, build='myMetadata')
 ```
 Would want something like this for all of the bumps available. 
  
 Current behavior results in:
 
 ```
 ver = semver.Version.parse('3.4.5+myMetadata')
 
ver.bump_patch()
Version(major=3, minor=4, patch=6, prerelease=None, build=None)
 ```
 Wiping my build metadata... 

# Additional context

I would be fine for a new API - but I basically just want access to bump a the specific version (major/minor/patch), without wiping everything else. Probably should work for pre-release info as well.

**Comment by tomschr** [comment]
Hi @KCSesh,
thanks for the report. Much appreciated! :+1: 

I see your point, but have you looked at the [`Version.replace()`](https://python-semver.readthedocs.io/en/latest/usage/replace-parts-of-a-version.html) function? This is exactly for such situations.

I think this should hopefully solve your issue. :slightly_smiling_face:

**Comment by KCSesh** [comment]
Thanks for the quick reply @tomschr! I wasn't aware of [Version.replace()](https://python-semver.readthedocs.io/en/latest/usage/replace-parts-of-a-version.html). 

I can make this work with Replace, however, I still want to use the power of `bump` and I guess I can do the following:

```
>>> ver = semver.Version.parse('3.4.5+myMetadata')
>>> ver.replace(patch=ver.bump_patch().patch)
Version(major=3, minor=4, patch=6, prerelease=None, build='myMetadata')
```

This does achieve what I was looking for.

I guess it still seems interesting to me that `bump` wipes build metadata - but that might be more for a separate discussion or maybe a misunderstanding I have on semantic versions.

**Comment by tomschr** [comment]
> Thanks for the quick reply @tomschr! I wasn't aware of Version.replace()

No problem. A lot of people miss the documentation. :wink: 


> I guess it still seems interesting to me that `bump` wipes build metadata - but that might be more for a separate discussion or maybe a misunderstanding I have on semantic versions.

This is how semver works. When you bump the patch version, all other are reset. A higher patch version "nullifies" the prerelease and build parts. This project follows this approach.

This is the normal behavior that seems to be consistent with other libraries, for example [node's semver](https://docs.npmjs.com/cli/v6/using-npm/semver):

```shell
$ npm install --save semver
$ ./node_modules/semver/bin/semver.js 3.4.5+myMetadata -i patch
3.4.6
```

Surprisingly, I couldn't find anything in the spec in regards to what happens to the prerelease and build parts when patch got increased. It looks like an omission, but it could be that I missed it. That sounds to me the spec lacks some precision.

**Comment by tomschr** [comment]
After digging into their semver issue tracker, I found the issue "Resetting of pre-release and build versions...".
It's kind of "out of scope". It seems they are currently undecided, but would like to willing to put an addition on the FAQ. However, this never happened. The issue itself was closed back in 2013.

That means to me there is no definitive answer. As a maintainer, if there is no updated semver specification in that regard, I don't see a need to change the existing behavior. Additionally, your issue can be solved by other means than modifying the existing bump functions. Other libraries follow the same approach than this project, so I don't want to destroy their expectations.

My conclusion would be to close your issue. Do you have any further ideas? One way to solve it would be to add it to the documentation and describe it there.

**Comment by tomschr** [comment]
@KCSesh If you have any further issues, ideas, or suggestions, let us know. In the meantime, I think this issue is resolved.

Many thanks!
