### ISSUE TITLE
code in "Combining Pydantic and semver" doc contains bug on serialization to json.

### ISSUE THREAD

**Issue by apiwat-chantawibul** [python-semver/python-semver#429]
# Situation

The code defining `ManifestVersion` in "Combining Pydantic and semver" documentation

https://github.com/python-semver/python-semver/blob/1f086326baf587a391c489cabc43e189b17d8fb6/docs/advanced/combine-pydantic-and-semver.rst?plain=1#L17-L60

has a bug when  `ManifestVersion`  is used for serialization to JSON, resulting in the following raised exception:

```
pydantic_core._pydantic_core.PydanticSerializationError: Error calling function `<lambda>`: AttributeError: 'Version' object has no attribute 'x'
```

# To Reproduce

```python
from pydantic import TypeAdapter
from semver import Version

version = Version.parse('1.2.3')
json_version = TypeAdapter(ManifestVersion).dump_json(version)
```

# Expected Behavior

is described in the following pytest module.
(with the `ManifestVersion` defined in `__init__.py`.)

```python
import json
import pytest
from pydantic import TypeAdapter
from semver import Version

from . import ManifestVersion


@pytest.mark.parametrize(
    'version',
    [
        '0.0.1',
        '1.9.8',
        '2.3.4-rc+generic',
        '11.12.13-0.1.2',
    ],
)
def test_serialize(version):
    expected_json = json.dumps(version).encode()
    expected_python = version = Version.parse(version)

    result_python = TypeAdapter(ManifestVersion).dump_python(version)
    result_json = TypeAdapter(ManifestVersion).dump_json(version)

    assert result_python == expected_python
    assert result_json == expected_json
```

# Solution

Change

https://github.com/python-semver/python-semver/blob/1f086326baf587a391c489cabc43e189b17d8fb6/docs/advanced/combine-pydantic-and-semver.rst?plain=1#L49-L51

to

```python
serialization = core_schema.to_string_ser_schema(),
```

**Comment by tomschr** [comment]
Thanks a lot! Merged and happy! :+1:
