### ISSUE TITLE
ValueError: 7.06.17705.0 is not valid SemVer string

### ISSUE THREAD

**Issue by libinmv** [python-semver/python-semver#437]
# Situation
`ValueError: 7.06.17705.0 is not valid SemVer string`
`ValueError: 7.06.17705 is not valid SemVer string`

Issue while parsing cybersecurity sensor versions from CrowdStrike
CrowdStrike sensor version example (7.06.17705.0)

# To Reproduce
```python
import semver

semver.Version.parse("7.06.17705.0")
semver.Version.parse("7.06.17705")
```

# Expected Behavior
### Input
```python
semver.Version.parse("7.06.17705.0") 
```
### Output
```
Version(major=7, minor=6, patch=17705, prerelease=None, build=None)
```

# Environment
- OS: MacOS
- Python version: Python 3.11.6
- Version of semver library: 3.0.2

# Additional context
Code works when input is
```python
semver.Version.parse("7.6.17705")
```

**Comment by tomschr** [comment]
Thanks @libinmv for your report! Very much appreciated. :+1: 

I fear, this is one of these situations where specification hits reality. :wink:

According to the semver spec, your input is invalid. This project follows the spec very closely. As such, I'm sorry I won't accept any changes that violates the spec or makes the library incompatible.

In this sense, the library behaves exactly how it is supposed to be. It's not a bug, but a feature. :slightly_smiling_face:

I know, this is frustrating. However, you could [create a sub class from the `Version` class](https://python-semver.readthedocs.io/en/latest/advanced/create-subclasses-from-version.html) and do the parsing there.

You could try something like this (untested):

```python
class CybersecurityVersion(Version):
    """
    A subclass of Version which allows versions from cybersecurity
    in the format of MAJOR.MINOR.PATCH.REST
    """

    @classmethod
    def parse(cls, version: str) -> "SemVerWithVPrefix":
        """
        Parse version string to a Version instance.

        :param version: regular version or in cybersecurity format
        :raises ValueError: when version is neither regular nor in cybersecurity format
        :return: a new instance
        """
        # First try to parse a regular version. If that fails, try
        # the cybersecurity format
        try:
           return super().parse(version)
        except ValueError:
           return super().parse(".".join(version.rsplit(".")[:3]))
```

The one problem left is to convert the "06" in "7.06.17705.0". [Semver states clearly](https://semver.org/#spec-item-2) (emphasize by me):

> 2. A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and **MUST NOT contain leading zeroes.**

That would be in violation of your use-case. I left this as an exercise for you to implement in the class above. :wink: 

If you use it in a Python session and pass it to the class from above, you get:

```python
>>> CybersecurityVersion.parse("7.6.17705.0")
CybersecurityVersion(major=7, minor=6, patch=17705, prerelease=None, build=None)
```

Hope this helps. If you see other options, let me know.
