### ISSUE TITLE
Support the `^` symbol in match()

### ISSUE THREAD

**Issue by onel** [python-semver/python-semver#443]
Really great work with this lib. It's a pleasure to use

# Situation
I'm using semver to parse and compare some npm package versions and the `^` is used a lot for dependencies.
It would be amazing if semver could support the symbol when calling `match()`.

# Possible Solution/Idea
Support the `^` symbol for the `match()` method

Eg

```py
ver = Version('1.1.0')
ver.match('^1.0.0')
# True

ver.match('^2.0.0')
# False
```

Right now it throws the error
```
ValueError: match_expr parameter should be in format <op><ver>, where <op> is one of ['<', '>', '==', '<=', '>=', '!=']. You provided: '^1.0.0'
```

**Comment by tomschr** [comment]
@onel Thank you Andrei! Much appreciated!

Yes, the error is to be expected. The `.match()` method is a very simplified way to compare two versions and I'd like to keep it that simple. Let me tell you why. :slightly_smiling_face: 

IMHO, the more extended comparisons are a bit out of scope for this method. I'm already working on these comparisons (like with the caret, tilde, ranges, etc.). We have already an issue for that: #241. However, it's currently not implemented yet.

I still trying to find a way how to implement this. Perhaps this method will become deprecated in the future. Or it will support more of the extended version comparison operators. I don't know yet, I haven't made up my mind. :wink: If you have any good ideas how we could proceed with issue #241, I'm all ears! :smile:

If you are okay with it, I'd like to close this issue. Hope I can find some time to work on that said issue so we could proceed with it.

How does it sound to you? Thanks!

**Comment by onel** [comment]
Sounds good, Tom.

If you are already working on a new version of the method that supports more options that is amazing.

Looking at #241 I see you are thinking of some options for the API. The ` in ` operator looks more pythonic but it doesn't make sense in all cases, like `<`.

In my opinion `match()` is a great method and name for the check that is doing. 
I understand if it needs to be rewritten but from the outside, it makes sense.
Are you thinking of a different method name to supports all the checks?

In my case, I just implemented a work around when the `^` is present, by using `.is_compatible()`. It gets the job done.

Sure, we can close this issue but please tell me how I can help.

**Comment by tomschr** [comment]
Thank you @onel for your answer! :+1: 

> you are thinking of some options for the API. The `in` operator looks more pythonic but it doesn't make sense in all cases, like `<`.

That's true. Probably that `in` operator was just a crazy idea. :smile: 


> In my opinion `match()` is a great method and name for the check that is doing.

Yes, maybe we should stick to that. It was a long time when I've looked at it and I may not remember all the details.

> I understand if it needs to be rewritten but from the outside, it makes sense.
> Are you thinking of a different method name to supports all the checks?

I'm not sure yet. Whatever makes sense.


> In my case, I just implemented a work around when the ^ is present, by using `.is_compatible()`. It gets the job done.

That's an interesting idea! That's another way to kind of split the work into several dedicated small functions. Could also work for caret and tilde (how to name those)?

But wouldn't that conflict with Python's Zen of "there should be only one obvious way"? :thinking: 

> please tell me how I can help.

Thank you for the offer! Glad you asked! :+1: 

Some time ago I've played with this issue and created PR#367. It's a draft and I put some ideas from other libraries (I think, it was from Node).

Perhaps my idea is a bit too complicated or over-engineered (as it introduced a specific `Spec` class). If you could have a look and tell me how to improve it, that would be great!

There are some unresolved questions in that PR that will influence the design. If you have some better idea or maybe something that works good in other libraries, I'd like to hear! :slightly_smiling_face: So it's basically the overall design that I'm struggle.

Let me know what we can improve together. I prefer a solution that:

* is pythonic.
* is easy to use and doesn't need a lot of mental capacity to understand it.
* is self-contained and doesn't depend on additional libraries.
* is well tested and documented.
* is easy to extend, debug, and to be mainted.
* is backward compatible (in other words, it doesn't break with the major release)

Apart from that, I'm open to any ideas or suggestions. Thanks!
