### ISSUE TITLE
Equality operators should not raise Exceptions on comparison to invalid semver constructs

### ISSUE THREAD

**Issue by well-dan** [python-semver/python-semver#444]
# Situation
I just cam across surprising behavior of the (in)equality operators, raising an exception on string comparison instead of returning False.  Since all operators are implemented using `Version.compare` it applies to all methods of comparing to invalid semver constructs.

# To Reproduce
```
>>> from semver import Version
>>> a = '2.0.7invalid'
>>> b = Version.parse('2.0.7')
>>> a == b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Local\lib\python\lib\site-packages\semver\version.py", line 51, in wrapper
    return operator(self, other)
  File "C:\Local\lib\python\lib\site-packages\semver\version.py", line 473, in __ne__
    return self.compare(other) != 0
  File "C:\Local\lib\python\lib\site-packages\semver\version.py", line 396, in compare
    other = cls.parse(other)
  File "C:\Local\lib\python\lib\site-packages\semver\version.py", line 646, in parse
    raise ValueError(f"{version} is not valid SemVer string")
ValueError: 2.0.7invalid is not valid SemVer string
>>>
```

# Expected Behavior
Equality operator should should return `False` instead of raising an exception. I'd expect comparison to other types to be implemented in the less specialized type.

# Environment
- OS: * (observed on Windows and Linux)
- Python version: * (observed in 3.10.11)
- Version of semver library: Issue still on main (observed in 3.0.2)

**Comment by tomschr** [comment]
@well-dan Thanks for your report.

If you want to read some details about the background, unfold the details section:

<details>
 <summary>Details of the comparison with invalid strings</summary>

----

The variable `a` a string object and variable `b` is of `Version` object. If you compare two objects, the `Version` class calls [`__eq__`](https://github.com/python-semver/python-semver/blob/master/src/semver/version.py#L469-L471):

```python
@_comparator
def __eq__(self, other: Comparable) -> bool:  # type: ignore
    return self.compare(other) == 0
```

This calls the [`.compare()`](https://github.com/python-semver/python-semver/blob/master/src/semver/version.py#L379-L425) method. The `.compare()` method checks for different objects and if it detects a string, it basically calls `Version.parse()` on that string:

```python
def compare(self, other: Comparable) -> int:
   """ ... """
   cls = type(self)
   if isinstance(other, String.__args__):  # type: ignore
      other = cls.parse(other)
```

This is where the "error" originated.

----

</details>

Well, if the string is _invalid_, it will be rejected by the `Version` class with a `ValueError` exception. This is normal behavior of the `.parse()` method.

So far, so good.

But should the comparison return always False even if the string is an invalid semver version? I don't think so for the following reasons:

* If a string can't be parsed into a valid semver version, how would the user know?
* As the string was already an invalid semver version it can never be successfully compared against a valid one.
* An exception helps to identify invalid versions and enforces strict adherence to the semver specification.
* This is where I think Python Zen's "Errors should never pass silently" applies.
* A change would make the comparison incompatible with previous releases

You have the same behavior if you want to parse a string into a `datetime` object. When you pass an invalid date, you get this exception:

```python
>>> from datetime import datetime
>>> datetime.strptime("2024", "%Y-%m-%d")
Traceback (most recent call last)
[...]
ValueError: time data '2024' does not match format '%Y-%m-%d'
```

Even a comparison wouldn't be possible.

In my humble opinion, it would do more harm than good.

If you really want this behavior, maybe [subclassing](https://python-semver.readthedocs.io/en/latest/advanced/create-subclasses-from-version.html) would be an option for you. Overwrite the `.compare` method, call `super().compare(...)` and catch any ValueError exceptions.

Sorry, but I would close this issue as invalid.

**Comment by tomschr** [comment]
@well-dan Just for your information, the "surprising" behavior was a long time ago documented in [Comparing Version](https://python-semver.readthedocs.io/en/latest/usage/compare-versions.html) under "A Version type and a str()". :slightly_smiling_face:
