### ISSUE TITLE
(not semver) Support for less than major.minor.patch

### ISSUE THREAD

**Issue by prikkeldraad** [python-semver/python-semver#70]
Althoug semver states that m.m.p should be present. That does not mean it always is. Some software only gives a major or major.minor number. I would like semver to parse those numbers with minor or patch numbers defaulting to 0. That's what is ment by those major only numbers anyway.

`version = semver.parse('3.0')`
Should result in 3.0.0

`version = semver.parse('10')`
Should result in 10.0.0

**Comment by k-bx** [comment]
I wouldn't mind having something like this, but it should be under an explicit API, separate from `semver.parse`, that would behave in a more "relaxed" way, documenting the differences in detail

**Comment by scls19fr** [comment]
Can we consider that passing a parameter named `strict` (with `True` as default) can be a solution ?

To be able to parse this kind of string we will have to do:

    version = semver.parse('10', strict=False)

I wonder if semver spec shouldn't be improved (asking at https://github.com/semver/semver ) to be more explicit about how parsing a version should behave

**Comment by k-bx** [comment]
No, please make a separate function with an obvious name that it's not Semver but something different. parse_relaxed might do

**Comment by scls19fr** [comment]
Ok

Adding a function such as `issemver` could also be interesting.

Maybe we should implement it this way.
```python
try:
    semver.parse(version)
    return True
except Exception as e:
    return False
```

**Comment by kxepal** [comment]
```
try:
    semver.parse(version)
except ValueError:
    return False
else:
    return True
```
If so.

**Comment by tomschr** [comment]
This issue is similar to others that we've closed. :wink: 

Currently, this is out of scope. However, we've documented it how to deal with such cases. Have a look at https://python-semver.readthedocs.io/en/latest/usage.html#dealing-with-invalid-versions

Thanks for all the input.
